version: '3'
services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus3
    restart: always
    ports:
      - 80:8081
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/nexus-data:/var/nexus-data:rw
    network_mode: bridge
