version: '3'
services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus3
    hostname: nexus3
    restart: always
    ports:
      - 8081:8081
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/nexus-data:/nexus-data:rw
    network_mode: bridge
