version: '3.8'
services:
  openspeedtest:
    image: openspeedtest/latest:latest
    container_name: openspeedtest
    hostname: openspeedtest
    ports:
      - 3001:3001
      - 3000:3000
    restart: always
    environment:
      - METRICS_ENABLED=true
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
