version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7.28
    restart: always
    ports:
      - 3306
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - "MYSQL_USER=sonar"
      - "MYSQL_PASSWORD=sonar"
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=sonar"

  sonarqube:
    container_name: sonarqube
    image: sonarqube:7.8-community
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./sonar-l10n-zh-plugin-1.28.jar:/opt/sonarqube/extensions/plugins/sonar-l10n-zh-plugin-1.28.jar:ro
    environment:
      - "sonar.jdbc.username=sonar"
      - "sonar.jdbc.password=sonar"
      - "sonar.jdbc.url=jdbc:mysql://mysql:3306/sonar?useUnicode=true&characterEncoding=utf8"
    depends_on:
      - mysql
