version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:13
    hostname: postgres
    restart: always
    ports:
      - 5432
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./postgresql/data:/var/lib/postgresql/data/:rw
    environment:
      - "POSTGRES_USER=sonar"
      - "POSTGRES_PASSWORD=sonar"
      - "POSTGRES_DB=sonar"

  sonarqube:
    container_name: sonarqube
    image: sonarqube:8.9.10-community
    hostname: sonarqube
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/opt/sonarqube/data:rw
      - ./extensions:/opt/sonarqube/extensions:rw
      - ./logs:/opt/sonarqube/logs:rw
      - ./conf:/opt/sonarqube/conf:rw
    environment:
      - "SONARQUBE_JDBC_USERNAME=sonar"
      - "SONARQUBE_JDBC_PASSWORD=sonar"
      - "SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar"
    depends_on:
      - postgres
