version: '3'
services:
  frps:
    image: snowdreamtech/frps:latest
    hostname: frps
    container_name: frps
    restart: always
    network_mode: host
    volumes:
     - ./frps.toml:/etc/frp/frps.toml
     - /etc/localtime:/etc/localtime
