version: '3'
services:
  iventoy:
    image: ziggyds/iventoy:latest
    container_name: iventoy
    hostname: iventoy
    restart: always
    privileged: true #must be true
    network_mode: host
#    ports:
#      - 26000:26000
#      - 16000:16000
#      - 10809:10809
#      - 67:67/udp
#      - 69:69/udp
    environment:
      - TZ: Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime
      - ./iso:/app/iso
#      - ./data:/app/data
      - ./log:/app/log
    environment:
      - AUTO_START_PXE=true # optional, true by default

#volumes:
#  config:
#    external: true
