version: '3'
services:
  keeweb:
    container_name: keeweb
    image: antelle/keeweb:latest
    hostname: keeweb
    restart: always
    ports:
      - 8443:443
    volumes:
      - /etc/localtime:/etc/localtime:rw
      - ./ssl:/etc/nginx/external:rw
      - ./webdav:/keeweb/webdav:rw
      - ./keeweb.conf:/etc/nginx/conf.d/keeweb.conf:rw
      - ./nginx.conf:/etc/nginx/nginx.conf:rw
      - ./keeweb.json:/keeweb/keeweb.json:rw
      - ./user.passwd:/etc/nginx/user.passwd:rw
