version: '3'
services:
  mysql-server:
    image: mysql:8.0.33
    container_name: mysql-server
    hostname: mysql-server
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mysql/conf/my.cnf:/etc/mysql/my.cnf:rw
      - ./mysql/data:/var/lib/mysql

  zabbix-server:
    image: zabbix/zabbix-server-mysql:centos-6.0-latest
    container_name: zabbix-server
    hostname: zabbix-server
    ports:
      - 10051:10051
    environment:
      - DB_SERVER_HOST=mysql-server
      - DB_SERVER_PORT=3306
      - DB_SERVER_DBNAME=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix
      - MYSQL_ROOT_PASSWORD=123456
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./server/alertscripts:/usr/lib/zabbix/alertscripts:rw
      - ./server/externalscripts:/usr/lib/zabbix/externalscripts:rw
#      - ./server/conf/zabbix_server.conf:/etc/zabbix/zabbix_server.conf:rw
    depends_on:
      - mysql-server

  zabbix-agent:
    image: zabbix/zabbix-agent:centos-6.0-latest
    container_name: zabbix-agent
    hostname: zabbix-agent
    ports:
      - 10050:10050
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_PORT=10051
    volumes:
      - /etc/localtime:/etc/localtime:ro
#      - ./agent/conf/zabbix_agentd.conf:/etc/zabbix/zabbix_agentd.conf:rw
      - ./agent/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:rw
      - ./agent/modules:/var/lib/zabbix/modules:rw
    depends_on:
      - zabbix-server

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:centos-6.0-latest
    container_name: zabbix-web
    hostname: zabbix-web
    ports:
      - 8080:8080
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - zabbix-server
