version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.17.5
    hostname: elasticsearch
    container_name: elasticsearch
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:rw
      - ./data:/usr/share/elasticsearch/data
      - ./logs:/usr/share/elasticsearch/logs
    environment:
      - node.name=elasticsearch
      - cluster.name=elk-single
      - path.data=/usr/share/elasticsearch/data
      - path.logs=/usr/share/elasticsearch/data
      - network.host=0.0.0.0
      - http.port=9200
      - transport.tcp.port=9300
      - bootstrap.memory_lock=true
      - discovery.type=single-node
#      - xpack.security.enabled=true  若需要身份验证，请取消注释
#      - ELASTIC_PASSWORD=elastic     若需要身份验证，请取消注释
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - http.cors.allow-headers="*"
    ulimits:
      memlock:
        hard: -1
        soft: -1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elasticsearch

  kibana:
    image: kibana:7.17.5
    container_name: kibana
    hostname: kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#      - ELASTICSEARCH_USERNAME=elastic  若es开启了身份验证，请取消注释
#      - ELASTICSEARCH_PASSWORD=elastic  若es开启了身份验证，请取消注释
    networks:
      - elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

networks:
  elasticsearch:
    driver: bridge
