version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.17.5
    hostname: elasticsearch
    container_name: elasticsearch
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:rw
      - ./config/jvm.options:/usr/share/elasticsearch/config/jvm.options
      - ./data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
