version: '3'
services:
  mysql:
    image: mysql:5.7.28
    container_name: mysql
    restart: always
    hostname: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    healthcheck:
      test: "mysql -h127.0.0.1 -P3306 -uroot -p123456 -e 'SHOW DATABASES;create database if not exists jumpserver;'"
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - /etc/localtime:/etc/localtime:rw
      - ./mysql/conf/my.cnf:/etc/mysql/my.cnf:rw
      - ./mysql/data:/var/lib/mysql:rw
    networks:
      net:
        ipv4_address: 172.16.238.2

  redis:
    image: redis:6.2.3
    restart: always
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
    volumes:
      - /etc/localtime:/etc/localtime:rw
      - ./redis/data:/data:rw
      - ./redis/conf/redis.conf:/etc/redis/redis.conf:rw
    healthcheck:
      test: "redis-cli -h 127.0.0.1 -p 6379 -a 123456 info Replication"
      interval: 10s
      timeout: 5s
      retries: 3
    command: redis-server /etc/redis/redis.conf
    networks:
      net:
        ipv4_address: 172.16.238.3

  core:
    image: jumpserver/core:v2.28.20
    container_name: jms_core
    hostname: jms_core
    restart: always
    tty: true
    command: start web
    environment:
      - SECRET_KEY=0imoXuphwWKE6b5JuJrJTNjvD9uGhw4sRrbW6TXddPOiX8bmnw
      - BOOTSTRAP_TOKEN=X3uaAUpf6x83QMcn
      - DEBUG=FALSE
      - LOG_LEVEL=ERROR
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=jumpserver
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=123456
    depends_on:
      - mysql
      - redis
    healthcheck:
      test: "curl -fsL http://localhost:8080/api/health/ > /dev/null"
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - /etc/localtime:/etc/localtime:rw
      - ./core/data:/opt/jumpserver/data
      - ./core/logs:/opt/jumpserver/logs
    networks:
      net:
        ipv4_address: 172.16.238.4

  celery:
    image: jumpserver/core:v2.28.20
    container_name: jms_celery
    hostname: jms_celery
    restart: always
    tty: true
    command: start task
    environment:
      - SECRET_KEY=0imoXuphwWKE6b5JuJrJTNjvD9uGhw4sRrbW6TXddPOiX8bmnw
      - BOOTSTRAP_TOKEN=X3uaAUpf6x83QMcn
      - DEBUG=FALSE
      - LOG_LEVEL=ERROR
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=jumpserver
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=123456
    depends_on:
      - mysql
      - redis
      - core
    healthcheck:
      test: "bash /opt/jumpserver/utils/check_celery.sh"
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - /etc/localtime:/etc/localtime:rw
      - ./core/data:/opt/jumpserver/data
      - ./core/logs:/opt/jumpserver/logs
    networks:
      net:
        ipv4_address: 172.16.238.5

  koko:
    image: jumpserver/koko:v2.28.20
    container_name: jms_koko
    hostname: jms_koko
    restart: always
    privileged: true
    tty: true
    environment:
      - CORE_HOST=http://core:8080
      - BOOTSTRAP_TOKEN=X3uaAUpf6x83QMcn
      - LOG_LEVEL=ERROR
    depends_on:
      - core
    healthcheck:
      test: "curl -fsL http://localhost:5000/koko/health/ > /dev/null"
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - /etc/localtime:/etc/localtime:rw
      - ./koko/data:/opt/koko/data
    ports:
      - 2222:2222
    networks:
      net:
        ipv4_address: 172.16.238.6

  lion:
    image: jumpserver/lion:v2.28.20
    container_name: jms_lion
    hostname: jms_lion
    restart: always
    tty: true
    environment:
      - CORE_HOST=http://core:8080
      - BOOTSTRAP_TOKEN=X3uaAUpf6x83QMcn
      - LOG_LEVEL=ERROR
    depends_on:
      - core
    healthcheck:
      test: "curl -fsL http://localhost:8081/lion/health/ > /dev/null"
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - /etc/localtime:/etc/localtime:rw
      - ./lion/data:/opt/lion/data
    networks:
      net:
        ipv4_address: 172.16.238.7

  magnus:
    image: jumpserver/magnus:v2.28.20
    container_name: jms_magnus
    hostname: jms_magnus
    restart: always
    tty: true
    environment:
      - CORE_HOST=http://core:8080
      - BOOTSTRAP_TOKEN=X3uaAUpf6x83QMcn
      - LOG_LEVEL=ERROR
    depends_on:
      - core
    healthcheck:
      test: "ps axu | grep -v 'grep' | grep magnus"
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - /etc/localtime:/etc/localtime:rw
      - ./magnus/data:/opt/magnus/data
    ports:
      - 33060:33060
      - 33061:33061
      - 54320:54320
      - 63790:63790
      - 15211:15211
      - 15212:15212
    networks:
      net:
        ipv4_address: 172.16.238.8

  web:
    image: jumpserver/web:v2.28.20
    container_name: jms_web
    hostname: jms_web
    restart: always
    tty: true
    depends_on:
      - core
    healthcheck:
      test: "curl -fsL http://localhost/ > /dev/null"
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - /etc/localtime:/etc/localtime:rw
      - ./core/data:/opt/jumpserver/data
      - ./nginx/data/logs:/var/log/nginx
    ports:
      - 80:80
    networks:
      net:
        ipv4_address: 172.16.238.9

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
