version: '3'
services:
  jenkins:
    image: jenkins
    container_name: jenkins
    restart: always
    ports:
      - 80:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/jenkins/.jenkins:/root/.jenkins:rw
    network_mode: bridge
