version: "3"
services:
  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    ports:
      - 9888:9000
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./data:/data:rw
      - ./public:/public:rw
