version: '3'
services:
  mysql:
    image: mysql:5.7.28
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mysqld.conf:/etc/mysql/mysql.conf.d/mysqld.cnf:rw
    network_mode: bridge
