version: "3"
services:
  gogs:
    image: cloudsx.top/gogs/gogs:latest
    container_name: gogs
    hostname: gogs
    restart: always
    ports:
      - "10022:22"
      - 3000:3000
    volumes:
      - ./gogs:/data

  mysql:
    image: registry.cn-hangzhou.aliyuncs.com/fastgpt/mysql:8.0.36
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: gogs
      MYSQL_USER: gogs
      MYSQL_PASSWORD: gogs
    volumes:
      - ./mysql:/var/lib/mysql
